# Extensions supportées -> langage Markdown associé :
# .cpp  -> cpp
# .c    -> c
# .h    -> cpp
# .hpp  -> cpp
# .ino  -> cpp
# .js   -> js
# .ts   -> ts
# .html -> html
# .css  -> css
# .py   -> python
# .json -> json
# .md   -> md

languages:
  .cpp: cpp
  .c: c
  .h: cpp
  .hpp: cpp
  .ino: cpp
  .js: js
  .ts: ts
  .html: html
  .css: css
  .py: python
  .json: json
  .vue: vue

sources:
  - ./example

docs:
  - input: ./docs/doc.md
    output: ./docs/doc_generated.md
    include_filename: true
